spring:
  datasource:
    url: ENC(Ut6VEtWN6/MombF/7N2owj2r4SazwMGto32gpzVsdPBgSqBSOqDS/sHnV7qLb5TyPrcm+w7gXr1OGHVYMq6M39z7e22MHtbE1QOJSxT06vJKYl0K6O8xXA==)
#    ENC(8moTJdaz9PLrriwOapxf5P7QrXoxfeI0j+hzXGKeLshMOCM9MuQDtY+yAP9yd9a4)
    username: ENC(vZkgke8ER30sYbI2bJBn6g==)
    password: ENC(kpY4jn3RSqS6IX3TF4QSMw1gSkVeQgEm)
#    ENC(kEJFPxxxZ7tpFzoRzZ5heQ==)

  jpa:
#    open-in-view: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


server:
  error:
    whitelabel:
      enabled: false


jasypt:
  encryptor:
    bean: jasyptStringEncryptor
#    password: ${JASYPT_PASSWORD}


logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: TRACE
        jdbc:
          datasource:
            DataSourceTransactionManager: DEBUG
        orm:
          jpa:
            JpaTransactionManager: DEBUG

      hibernate:
        #JPA log
        resource:
          transaction: DEBUG
        #JPA SQL
        SQL: DEBUG

  #slack log 연결
  slack:
    webhook-uri: ENC(U+fzmnjmaL8ycY1Ugk/9SnHMEe8omSMJec2heUyip9uU0FUzdmP2zwwA2gRLITGRAgAbSGQMLXmpg9R1VWatAmzb6wX75PsQ6hK9G3xHCO6tfs4xBPS3qifiArVZdYmW)
  config: classpath:logback-spring.xml

#API 필수 정보
open_api:
  naver:
    Client_ID: ENC(IKvlU8PFnYwk8dVDPrCKTHnj6cmU2AVPdtDCu49qUPg=)
    Client_Secret: ENC(VVIIlbgGy58tdkgrAUk7AuBlEE8o3b5U)
