spring:
  datasource:
    url: ENC(KiAsU+eEUig6hBE0/6g7640NK5gXd8n004/4CLYJZJEH5+uof5PO/nE+5h7w9Km0)
    username: ENC(zmLkHZZhjFlp2SLpqhqh/A==)
    password: ENC(KsRUhNYxCuYWWaE29/nv6g==)

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


server:
  error:
    whitelabel:
      enabled: false


jasypt:
  encryptor:
    bean: jasyptStringEncryptor
#    password: ${JASYPT_PASSWORD}


logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: TRACE
        jdbc:
          datasource:
            DataSourceTransactionManager: DEBUG
        orm:
          jpa:
            JpaTransactionManager: DEBUG

      hibernate:
        #JPA log
        resource:
          transaction: DEBUG
        #JPA SQL
        SQL: DEBUG

#API 필수 정보
open_api:
  naver:
    Client_ID: ENC(nLH6e1kgYsR04iGXA4YR4rmQ1ik0yM1cSwOKxiM4CSc=)
    Client_Secret: ENC(NBrP7dSYnPTh9fa6rgkeueqAqV1bTTVI)
